In [ ]:
pip install mediapipe


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.6/35.6 MB 17.9 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-manylinux1_x86_64.whl (166.0 MB)
  Using cached nvidia_nvtx_cu12-12.1.105-py3-none-manyl

In [ ]:
pip  install tracker cvzone ultralytics

In [ ]:
import os
import cv2
import mediapipe as mp
import time

# Set CUDA_VISIBLE_DEVICES to an empty string to force CPU execution
os.environ['CUDA_VISIBLE_DEVICES'] = ''

mp_objectron = mp.solutions.objectron
mp_drawing = mp.solutions.drawing_utils

# Specify the path to your video file
video_path = r"/content/drive/MyDrive/movement /lefttoright.mp4"

cap = cv2.VideoCapture(video_path)

# Define the codec and create VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'XVID')
output_file = 'output8.avi'

# Get original video properties
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)

out = cv2.VideoWriter(output_file, fourcc, fps, (width, height))

start_time = 0 # Start time in seconds
end_time =  10 # End time in seconds

# Calculate the frame indices corresponding to the start and end times
start_frame = int(start_time * fps)
end_frame = int(end_time * fps)

with mp_objectron.Objectron(static_image_mode=False,
                            max_num_objects=2,
                            min_detection_confidence=0.5,
                            min_tracking_confidence=0.8,
                            model_name='Cup') as objectron:
    frame_index = 0
    while cap.isOpened():
        success, image = cap.read()
        if not success:
            print("Failed to read from video file.")
            break

        if frame_index < start_frame:
            # Skip frames until reaching the start time
            frame_index += 1
            continue
        elif frame_index > end_frame:
            # Stop processing frames after the end time
            break

        start = time.time()
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False
        results = objectron.process(image)

        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        if results.detected_objects:
            for detected_object in results.detected_objects:
                mp_drawing.draw_landmarks(image, detected_object.landmarks_2d, mp_objectron.BOX_CONNECTIONS)
                mp_drawing.draw_axis(image, detected_object.rotation, detected_object.translation)
                x = results.detected_objects
                print(x[0].rotation)
                print(x[0].translation)
                print(x[0].scale)

                # Extracting desired information

                print('*')

        end = time.time()
        totalTime = end - start
        fbs = 1 / totalTime


        # Write the frame with annotations to the output video file
        out.write(image)

        frame_index += 1

    # Release the VideoCapture and VideoWriter objects
    cap.release()
    out.release()


[[-0.96426386 -0.11128177  0.57711881]
 [-0.08125918  0.96873897  0.27491289]
 [-0.25217459  0.22172311 -0.76899713]]
[ 0.27799916  0.01609001 -0.40612897]
[0.09362797 0.19629493 0.10821325]
*
[[-0.94229084 -0.09543718  0.59398246]
 [-0.08996973  0.97497737  0.26606834]
 [-0.32248014  0.20077609 -0.75920534]]
[ 0.27664882  0.0166598  -0.40401408]
[0.09399333 0.19262046 0.11565611]
*
[[-0.98155272 -0.08333416  0.59147066]
 [ 0.06773145  0.97296202  0.35409302]
 [-0.17879353  0.21540801 -0.72441733]]
[ 0.27374539  0.01494835 -0.4055272 ]
[0.13537544 0.21681046 0.14551422]
*
[[-0.96577609 -0.13230944  0.42778346]
 [-0.22067358  0.95425183  0.43019471]
 [ 0.13630849  0.26813841 -0.79494268]]
[ 0.27528858  0.01626806 -0.41054815]
[0.13757858 0.18353677 0.15752025]
*
[[-0.89979011 -0.53582633 -0.12438903]
 [-0.37846094 -0.03639243  0.98493844]
 [-0.21713011  0.84354347 -0.12009731]]
[ 0.2785562   0.02676874 -0.42132741]
[0.0580701  0.04397423 0.10743344]
*
[[-0.99857861 -0.06798729  0.543284

In [ ]:
import numpy as np

# Sample data
sample_data = {
    "rotation": np.array([[0.02643959, -0.01697304, -0.97913629],
                          [-0.69238818, 0.99677402, 0.08258526],
                          [0.72104055, 0.07844639, -0.18566644]]),
    "translation": np.array([0.00551959, 0.12201118, -0.48317826]),
    "scale": np.array([0.11630733, 0.23111713, 0.15568599]),
}

def convert_to_kitti(sample_data):
    # Extracting data
    rotation = sample_data["rotation"]
    translation = sample_data["translation"]
    scale = sample_data["scale"]

    dimensions = scale
    location = translation
    rotation_y = np.arcsin(-rotation[0, 2])  # Calculating rotation_y

    # Write KITTI format string
    kitti_format = f"{dimensions[0]} {dimensions[1]} {dimensions[2]} " \
                   f"{location[0]} {location[1]} {location[2]} " \
                   f"{rotation_y} "  # Score is assumed to be 0.0

    return kitti_format

# Convert sample data to KITTI format
kitti_data = convert_to_kitti(sample_data)
print(kitti_data)

0.11630733 0.23111713 0.15568599 0.00551959 0.12201118 -0.48317826 1.3661665858920293 


In [ ]:
import cv2
import math
import mediapipe as mp
from ultralytics import YOLO

mp_objectron = mp.solutions.objectron
mp_drawing = mp.solutions.drawing_utils

model_yolo = YOLO("/content/yolov8n.pt")

classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"]

# Create an instance of the Objectron model
objectron = mp_objectron.Objectron()
def convert_to_kitti(sample_data):
    # Extracting data
    rotation = sample_data["rotation"]
    translation = sample_data["translation"]
    scale = sample_data["scale"]

    dimensions = scale
    location = translation
    rotation_y = np.arcsin(-rotation[0, 2])  # Calculating rotation_y

    # Write KITTI format string
    kitti_format = [dimensions[0], dimensions[1], dimensions[2], location[0], location[1], location[2], rotation_y ]

    return kitti_format


def detect_yolo(image):
    results = model_yolo(image, stream=True)
    objects_info = []
    for r in results:
        boxes = r.boxes
        for box in boxes:
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            conf = math.ceil((box.conf[0]*100))/100
            cls = int(box.cls[0])
            object_info = {
                "class": classNames[cls],
                "confidence": conf,
                "bounding_box": (x1, y1, x2, y2)
            }
            objects_info.append(object_info)
    return objects_info

def detect_objectron(image):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = objectron.process(image)
    object_info = []
    if results.detected_objects:
        for detected_object in results.detected_objects:
            x = results.detected_objects
            rotation = x[0].rotation
            translation = x[0].translation
            scale = x[0].scale
            object_info.append({
                "rotation": rotation,
                "translation": translation,
                "scale": scale
            })
    return object_info

def process_frame(image):
    yolo_results = detect_yolo(image)
    if not yolo_results:
        return  # No objects detected by YOLO, so return without further processing

    objectron_results = detect_objectron(image)
    l = []
    if objectron_results:
        for i in yolo_results:
            if i['class'] == 'cup':
                 l.append(i['class'])
                 for j in i['bounding_box']:
                     l.append(j)
        for obj_result in objectron_results:
            sample_data = {
                  "rotation": np.array(obj_result['rotation']),
                  "translation": np.array(obj_result['translation']),
                  "scale": np.array( obj_result['scale']),
            }

            kitti_data = convert_to_kitti(sample_data)
            for i in kitti_data:
                l.append(i)
    if len(l) == 12:
      print(l)


# Specify the path to your video file
video_path =r"/content/video_20240317_102925.mp4"

cap = cv2.VideoCapture(video_path)
if not cap.isOpened():
    print("Error: Failed to open video file.")

# Set the start and end time for processing
start_time = 10 # Start time in seconds
end_time = 20 # End time in seconds (60 minutes)
frame_interval = 1  # Process one frame every 3 seconds

fps = cap.get(cv2.CAP_PROP_FPS)
start_frame = int(start_time * fps)
end_frame = int(end_time * fps)

current_frame = 0
while cap.isOpened():
    success, image = cap.read()
    if not success:
        print("Error: Failed to read frame from video.")
        break

    if current_frame < start_frame:
        current_frame += 1
        continue

    if current_frame > end_frame:
        break

    # Process frame every `frame_interval` seconds
    if current_frame % (fps * frame_interval) == 0:
        process_frame(image)

    current_frame += 1

cap.release()
cv2.destroyAllWindows()



0: 384x640 3 bottles, 2 beds, 181.3ms
Speed: 5.9ms preprocess, 181.3ms inference, 1.3ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 bottles, 1 cup, 1 bed, 142.4ms
Speed: 3.5ms preprocess, 142.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 3 bottles, 1 cup, 1 bed, 140.8ms
Speed: 4.5ms preprocess, 140.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 bottles, 1 cup, 1 bed, 141.7ms
Speed: 6.1ms preprocess, 141.7ms inference, 1.1ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 cup, 1 bed, 139.8ms
Speed: 3.8ms preprocess, 139.8ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 2 cups, 144.4ms
Speed: 6.1ms preprocess, 144.4ms inference, 1.2ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bottle, 1 cup, 1 dining table, 160.5ms
Speed: 3.8ms preprocess, 160.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)

0: 384x640 1 bottle, 1 c

In [ ]:
import numpy as np

# Sample data
sample_data = {
    "rotation": np.array([[0.02643959, -0.01697304, -0.97913629],
                          [-0.69238818, 0.99677402, 0.08258526],
                          [0.72104055, 0.07844639, -0.18566644]]),
    "translation": np.array([0.00551959, 0.12201118, -0.48317826]),
    "scale": np.array([0.11630733, 0.23111713, 0.15568599]),
}

def convert_to_kitti(sample_data):
    # Extracting data
    rotation = sample_data["rotation"]
    translation = sample_data["translation"]
    scale = sample_data["scale"]

    dimensions = scale
    location = translation
    rotation_y = np.arcsin(-rotation[0, 2])  # Calculating rotation_y

    # Write KITTI format string
    kitti_format = f"{dimensions[0]} {dimensions[1]} {dimensions[2]} " \
                   f"{location[0]} {location[1]} {location[2]} " \
                   f"{rotation_y} "  # Score is assumed to be 0.0

    return kitti_format

# Convert sample data to KITTI format
kitti_data = convert_to_kitti(sample_data)
print(kitti_data)

In [ ]:
import cv2
import math
import mediapipe as mp
from ultralytics import YOLO
import numpy as np

mp_objectron = mp.solutions.objectron
mp_drawing = mp.solutions.drawing_utils

# Initialize YOLO model
model_yolo = YOLO("/content/yolov8n.pt")

# Define class names for YOLO
classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"]

# Create an instance of the Objectron model
objectron = mp_objectron.Objectron()

def convert_to_kitti(sample_data):
    # Extracting data
    rotation = sample_data["rotation"]
    translation = sample_data["translation"]
    scale = sample_data["scale"]

    dimensions = scale
    location = translation
    rotation_y = np.arcsin(-rotation[0, 2])  # Calculating rotation_y

    # Write KITTI format string
    kitti_format = [dimensions[0], dimensions[1], dimensions[2], location[0], location[1], location[2], rotation_y ]

    return kitti_format

def detect_yolo(image):
    results = model_yolo(image, stream=True)
    objects_info = []
    for r in results:
        boxes = r.boxes
        for box in boxes:
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            conf = math.ceil((box.conf[0]*100))/100
            cls = int(box.cls[0])
            object_info = {
                "class": classNames[cls],
                "confidence": conf,
                "bounding_box": (x1, y1, x2, y2)
            }
            objects_info.append(object_info)
    return objects_info

def detect_objectron(image):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = objectron.process(image)  # Process the image with the Objectron model
    object_info = []
    if results.detected_objects:
        for detected_object in results.detected_objects:
            x = results.detected_objects
            rotation = x[0].rotation
            translation = x[0].translation
            scale = x[0].scale
            object_info.append({
                "rotation": rotation,
                "translation": translation,
                "scale": scale
            })
    return object_info

def process_frame(image):
    yolo_results = detect_yolo(image)
    print(yolo_results)
    if not yolo_results:
        return  # No objects detected by YOLO, so return without further processing

    objectron_results = detect_objectron(image)
    print(objectron_results)
    l = []
    if objectron_results:
        for i in yolo_results:
            if i['class'] == 'cup':
                 l.append(i['class'])
                 for j in i['bounding_box']:
                     l.append(j)
        for obj_result in objectron_results:
            sample_data = {
                  "rotation": np.array(obj_result['rotation']),
                  "translation": np.array(obj_result['translation']),
                  "scale": np.array( obj_result['scale']),
            }

            kitti_data = convert_to_kitti(sample_data)
            for i in kitti_data:
                l.append(i)

    print(l)

# Specify the path to your video file
video_path =r"/content/InShot_20240317_114822677.mp4"

cap = cv2.VideoCapture(video_path)
if not cap.isOpened():
    print("Error: Failed to open video file.")

# Set the start and end time for processing
start_time = 0 # Start time in seconds
end_time = 35 # End time in seconds (60 minutes)
frame_interval = 1  # Process one frame every 3 seconds

fps = cap.get(cv2.CAP_PROP_FPS)
start_frame = int(start_time * fps)
end_frame = int(end_time * fps)

current_frame = 0
while cap.isOpened():
    success, image = cap.read()
    if not success:
        print("Error: Failed to read frame from video.")
        break

    if current_frame < start_frame:
        current_frame += 1
        continue

    if current_frame > end_frame:
        break

    # Process frame every `frame_interval` seconds
    if current_frame % (fps * frame_interval) == 0:
        process_frame(image)

    current_frame += 1

cap.release()
cv2.destroyAllWindows()



0: 384x640 (no detections), 183.9ms
Speed: 5.6ms preprocess, 183.9ms inference, 0.7ms postprocess per image at shape (1, 3, 384, 640)
[]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import cv2
import math
import mediapipe as mp
from ultralytics import YOLO
import numpy as np

mp_objectron = mp.solutions.objectron
mp_drawing = mp.solutions.drawing_utils

# Initialize YOLO model
model_yolo = YOLO("/content/yolov8l.pt")

# Define class names for YOLO
classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"]


# Create an instance of the Objectron model specific to cups
objectron = mp_objectron.Objectron(static_image_mode=False,
                                    max_num_objects=2,
                                    min_detection_confidence=0.5,
                                    min_tracking_confidence=0.8,
                                    model_name='Cup')

def convert_to_kitti(sample_data):
    # Extracting data
    rotation = sample_data["rotation"]
    translation = sample_data["translation"]
    scale = sample_data["scale"]

    dimensions = scale
    location = translation
    rotation_y = np.arcsin(-rotation[0, 2])  # Calculating rotation_y

    # Write KITTI format string
    kitti_format = [dimensions[0], dimensions[1], dimensions[2], location[0], location[1], location[2], rotation_y ]

    return kitti_format

def detect_yolo(image):
    results = model_yolo(image, stream=True)
    objects_info = []
    for r in results:
        boxes = r.boxes
        for box in boxes:
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            conf = math.ceil((box.conf[0]*100))/100
            cls = int(box.cls[0])
            object_info = {
                "class": classNames[cls],
                "confidence": conf,
                "bounding_box": (x1, y1, x2, y2)
            }
            objects_info.append(object_info)
    return objects_info

def detect_objectron(image):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = objectron.process(image)  # Process the image with the Objectron model
    object_info = []
    if results.detected_objects:
        for detected_object in results.detected_objects:
            x = results.detected_objects
            rotation = x[0].rotation
            translation = x[0].translation
            scale = x[0].scale
            object_info.append({
                "rotation": rotation,
                "translation": translation,
                "scale": scale
            })
    return object_info

def process_frame(image):
    yolo_results = detect_yolo(image)

    if not yolo_results:
        return  # No objects detected by YOLO, so return without further processing

    objectron_results = detect_objectron(image)
    l = []
    if objectron_results:
        for i in yolo_results:
            if i['class'] == 'cup':
                 l.append(i['class'])
                 for j in i['bounding_box']:
                     l.append(j)
        for obj_result in objectron_results:
            sample_data = {
                  "rotation": np.array(obj_result['rotation']),
                  "translation": np.array(obj_result['translation']),
                  "scale": np.array( obj_result['scale']),
            }

            kitti_data = convert_to_kitti(sample_data)
            for i in kitti_data:
                l.append(i)
    return l

# Specify the path to your video file
video_path =r"/content/drive/MyDrive/movement /forward.mp4"

cap = cv2.VideoCapture(video_path)
if not cap.isOpened():
    print("Error: Failed to open video file.")

fps = cap.get(cv2.CAP_PROP_FPS)

current_frame = 0
output = []
while cap.isOpened():
    success, image = cap.read()
    if not success:
        print("Error: Failed to read frame from video.")
        break

    # Process frame every `frame_interval` seconds
    x = process_frame(image)
    output.append(x)
    # Print image size
    height, width, _ = image.shape
    print("Image Size: {}x{}".format(width, height))

cap.release()
cv2.destroyAllWindows()


In [ ]:
import cv2
import math
import mediapipe as mp
from ultralytics import YOLO
import numpy as np

mp_objectron = mp.solutions.objectron
mp_drawing = mp.solutions.drawing_utils

# Initialize YOLO model
model_yolo = YOLO("/content/yolov8l.pt")

# Define class names for YOLO
classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"]


# Create an instance of the Objectron model specific to cups
objectron = mp_objectron.Objectron(static_image_mode=False,
                                    max_num_objects=2,
                                    min_detection_confidence=0.5,
                                    min_tracking_confidence=0.8,
                                    model_name='Cup')

def convert_to_kitti(sample_data):
    # Extracting data
    rotation = sample_data["rotation"]
    translation = sample_data["translation"]
    scale = sample_data["scale"]

    dimensions = scale
    location = translation
    rotation_y = np.arcsin(-rotation[0, 2])  # Calculating rotation_y

    # Write KITTI format string
    kitti_format = [dimensions[0], dimensions[1], dimensions[2], location[0], location[1], location[2], rotation_y ]

    return kitti_format

def detect_yolo(image):
    results = model_yolo(image, stream=True)
    objects_info = []
    for r in results:
        boxes = r.boxes
        for box in boxes:
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            conf = math.ceil((box.conf[0]*100))/100
            cls = int(box.cls[0])
            object_info = {
                "class": classNames[cls],
                "confidence": conf,
                "bounding_box": (x1, y1, x2, y2)
            }
            objects_info.append(object_info)
    return objects_info

def detect_objectron(image):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = objectron.process(image)  # Process the image with the Objectron model
    object_info = []
    if results.detected_objects:
        for detected_object in results.detected_objects:
            x = results.detected_objects
            rotation = x[0].rotation
            translation = x[0].translation
            scale = x[0].scale
            object_info.append({
                "rotation": rotation,
                "translation": translation,
                "scale": scale
            })
    return object_info

def process_frame(image):
    yolo_results = detect_yolo(image)

    if not yolo_results:
        return  # No objects detected by YOLO, so return without further processing

    objectron_results = detect_objectron(image)
    l = []
    if objectron_results:
        for i in yolo_results:
            if i['class'] == 'cup':
                 l.append(i['class'])
                 for j in i['bounding_box']:
                     l.append(j)
        for obj_result in objectron_results:
            sample_data = {
                  "rotation": np.array(obj_result['rotation']),
                  "translation": np.array(obj_result['translation']),
                  "scale": np.array( obj_result['scale']),
            }

            kitti_data = convert_to_kitti(sample_data)
            for i in kitti_data:
                l.append(i)
    return l

# Specify the path to your video file
video_path =r"/content/drive/MyDrive/movement /forward.mp4"

cap = cv2.VideoCapture(video_path)
if not cap.isOpened():
    print("Error: Failed to open video file.")

fps = cap.get(cv2.CAP_PROP_FPS)

current_frame = 0
output = []
while cap.isOpened():
    success, image = cap.read()
    if not success:
        print("Error: Failed to read frame from video.")
        break

    # Process frame every `frame_interval` seconds
    x = process_frame(image)
    cp = []
    output.append(x)


cap.release()
cv2.destroyAllWindows()


In [ ]:
len(output)

240

In [ ]:
# Print image size
    height, width, _ = image.shape
    print("Image Size: {}x{}".format(width, height))
    print(x)
    if x != [] and len(x) == 12:
      top_left_corner = (x[1],x[2])
      bottom_right_corner = (x[3],x[4])
      center_point = find_center_point(width, height, top_left_corner, bottom_right_corner)
      print("Center Point:", center_point)
      cp.append(center_point)

[(797.5, 444.0)]


In [ ]:
import cv2
import math
import mediapipe as mp
from ultralytics import YOLO
import numpy as np

mp_objectron = mp.solutions.objectron
mp_drawing = mp.solutions.drawing_utils

# Initialize YOLO model
model_yolo = YOLO("/content/yolov8l.pt")

# Define class names for YOLO
classNames = ["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat",
              "traffic light", "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat",
              "dog", "horse", "sheep", "cow", "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella",
              "handbag", "tie", "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "baseball bat",
              "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass", "cup",
              "fork", "knife", "spoon", "bowl", "banana", "apple", "sandwich", "orange", "broccoli",
              "carrot", "hot dog", "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed",
              "diningtable", "toilet", "tvmonitor", "laptop", "mouse", "remote", "keyboard", "cell phone",
              "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
              "teddy bear", "hair drier", "toothbrush"]


# Create an instance of the Objectron model specific to cups
objectron = mp_objectron.Objectron(static_image_mode=False,
                                    max_num_objects=2,
                                    min_detection_confidence=0.5,
                                    min_tracking_confidence=0.8,
                                    model_name='Cup')

def convert_to_kitti(sample_data):
    # Extracting data
    rotation = sample_data["rotation"]
    translation = sample_data["translation"]
    scale = sample_data["scale"]

    dimensions = scale
    location = translation
    rotation_y = np.arcsin(-rotation[0, 2])  # Calculating rotation_y

    # Write KITTI format string
    kitti_format = [dimensions[0], dimensions[1], dimensions[2], location[0], location[1], location[2], rotation_y ]

    return kitti_format

def detect_yolo(image):
    results = model_yolo(image, stream=True)
    objects_info = []
    for r in results:
        boxes = r.boxes
        for box in boxes:
            x1, y1, x2, y2 = box.xyxy[0]
            x1, y1, x2, y2 = int(x1), int(y1), int(x2), int(y2)
            conf = math.ceil((box.conf[0]*100))/100
            cls = int(box.cls[0])
            object_info = {
                "class": classNames[cls],
                "confidence": conf,
                "bounding_box": (x1, y1, x2, y2)
            }
            objects_info.append(object_info)
    return objects_info

def detect_objectron(image):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image.flags.writeable = False
    results = objectron.process(image)  # Process the image with the Objectron model
    object_info = []
    if results.detected_objects:
        for detected_object in results.detected_objects:
            x = results.detected_objects
            rotation = x[0].rotation
            translation = x[0].translation
            scale = x[0].scale
            object_info.append({
                "rotation": rotation,
                "translation": translation,
                "scale": scale
            })
    return object_info

def process_frame(image):
    yolo_results = detect_yolo(image)

    if not yolo_results:
        return  # No objects detected by YOLO, so return without further processing

    objectron_results = detect_objectron(image)
    l = []
    if objectron_results:
        for i in yolo_results:
            if i['class'] == 'cup':
                 l.append(i['class'])
                 for j in i['bounding_box']:
                     l.append(j)
        for obj_result in objectron_results:
            sample_data = {
                  "rotation": np.array(obj_result['rotation']),
                  "translation": np.array(obj_result['translation']),
                  "scale": np.array( obj_result['scale']),
            }

            kitti_data = convert_to_kitti(sample_data)
            for i in kitti_data:
                l.append(i)
    return l

import os

# Specify the path to your video file
video_path = r"/content/drive/MyDrive/movement /forward.mp4"

# Get total number of frames in the video
cap = cv2.VideoCapture(video_path)
if not cap.isOpened():
    print("Error: Failed to open video file.")

total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
print(total_frames)
cap.release()

# Select 100 evenly distributed frames
frames_to_process = np.linspace(0, total_frames - 1, num=10, dtype=np.int64)

# Process selected frames
output = []
cap = cv2.VideoCapture(video_path)
for frame_num in frames_to_process:
    cap.set(cv2.CAP_PROP_POS_FRAMES, frame_num)
    success, image = cap.read()
    if not success:
        print("Error: Failed to read frame from video.")
        break

    # Process frame
    x = process_frame(image)
    if x is not None:  # Check if any objects were detected
        output.append(x)
    height, width, _ = image.shape
    print("Image Size: {}x{}".format(width, height))


cap.release()
cv2.destroyAllWindows()


In [ ]:
output

In [ ]:
b = []

for i in output:

    if i != None:
      if len(i) == 12 and i != []:

        b.append(i)

In [ ]:
len(b)

0

In [ ]:
b

In [ ]:
for i in b:
  i[0] = 9
  print(i)

[9, 532, 354, 914, 679, 0.14608444273471832, 0.23693090677261353, 0.14371249079704285, -0.10829945653676987, 0.023294849321246147, -0.4650692343711853, 0.3438283455332299]
[9, 529, 356, 913, 685, 0.14689144492149353, 0.23973354697227478, 0.1393606811761856, -0.11154793947935104, 0.016667386516928673, -0.4660412073135376, 0.35322758764630785]
[9, 524, 358, 914, 691, 0.14881128072738647, 0.24284633994102478, 0.14219585061073303, -0.11214595288038254, 0.011801342479884624, -0.4663623571395874, 0.3504135397292102]
[9, 514, 359, 914, 703, 0.1579485386610031, 0.24501299858093262, 0.1439911127090454, -0.11248185485601425, 0.010500802658498287, -0.46428626775741577, 0.38307059227559553]
[9, 509, 357, 916, 705, 0.14948275685310364, 0.24744074046611786, 0.1405186951160431, -0.11181961745023727, 0.009841665625572205, -0.464760959148407, 0.3543544364907492]
[9, 505, 355, 916, 705, 0.14611440896987915, 0.24740611016750336, 0.14145511388778687, -0.11182725429534912, 0.010564441792666912, -0.46521946

In [ ]:
def append_last_to_first_for_all_data(data_list):
    updated_data = []
    for sublist in data_list:
        print(sublist)
        last_value = sublist[-1]  # Get the last value in the last sublist
        sublist.insert(0,last_value)  # Append the last value to the first sublist
        updated_data.append(sublist)
        sublist.pop()
    return updated_data


updated_list = append_last_to_first_for_all_data(b)
print(updated_list)

[9, 532, 354, 914, 679, 0.14608444273471832, 0.23693090677261353, 0.14371249079704285, -0.10829945653676987, 0.023294849321246147, -0.4650692343711853, 0.3438283455332299]
[9, 529, 356, 913, 685, 0.14689144492149353, 0.23973354697227478, 0.1393606811761856, -0.11154793947935104, 0.016667386516928673, -0.4660412073135376, 0.35322758764630785]
[9, 524, 358, 914, 691, 0.14881128072738647, 0.24284633994102478, 0.14219585061073303, -0.11214595288038254, 0.011801342479884624, -0.4663623571395874, 0.3504135397292102]
[9, 514, 359, 914, 703, 0.1579485386610031, 0.24501299858093262, 0.1439911127090454, -0.11248185485601425, 0.010500802658498287, -0.46428626775741577, 0.38307059227559553]
[9, 509, 357, 916, 705, 0.14948275685310364, 0.24744074046611786, 0.1405186951160431, -0.11181961745023727, 0.009841665625572205, -0.464760959148407, 0.3543544364907492]
[9, 505, 355, 916, 705, 0.14611440896987915, 0.24740611016750336, 0.14145511388778687, -0.11182725429534912, 0.010564441792666912, -0.46521946

In [ ]:
import pandas as pd

# Example list of lists
data =b

# Define column names
columns = ['Rotation_y', 'encoded_column', 'BoundingBox_X1', 'BoundingBox_Y1', 'BoundingBox_X2', 'BoundingBox_Y2', 'Location_x', 'Location_y',
       'Location_z', 'Dimensions_Length', 'Dimensions_Width',
       'Dimensions_Height' ]

# Create a DataFrame from the list of lists and specify column names
df = pd.DataFrame(data, columns=columns)

# Save DataFrame to Excel file
excel_filename = 'forward.xlsx'
df.to_excel(excel_filename, index=False)

print(f"DataFrame saved to '{excel_filename}'")


DataFrame saved to 'forward.xlsx'


In [ ]:
()